### ISSUE TITLE
linuxmuster-import-subnets - crash

### ISSUE THREAD

**Issue by white-rabbit07** [linuxmuster/linuxmuster-base7#101]
Hallo.
Ich habe linuxmuster-import-subnets laufen lassen -- es läuft aber nicht (mehr) durch! Zunächst sieht alles gut aus, doch dann erscheint diese Meldung:
`[...]
#### * Upload finished successfully.                                      ####
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 332, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='firewall.linuxmuster.my-domain.de', port=443): Max retries exceeded with url: /api/routes/routes/reconfigure (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/linuxmuster-import-subnets", line 454, in <module>
    changed = firewallApi('post', '/routes/routes/reconfigure')
  File "/usr/lib/linuxmuster/functions.py", line 536, in firewallApi
    req = requests.post(url, verify=constants.FWFULLCHAIN, auth=(apikey, apisecret))
  File "/usr/lib/python3/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='firewall.linuxmuster.my-domain.de', port=443): Max retries exceeded with url: /api/routes/routes/reconfigure (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))`

**Comment by HappyBasher** [comment]
I cannot reproduce this. Seems to be misconfiguration. firewall.linuxmuster.my-domain.de is no valid host/domainname. Please get support on ask.linuxmuster.net.

**Comment by zefanja** [comment]
> firewall.linuxmuster.my-domain.de is no valid host/domainname

It is, we use the same here without problems, like `firewall.ad.example.com`

**Comment by HappyBasher** [comment]
Is it only when he is the owner of my-domain.de. But this is no support forum.

**Comment by HappyBasher** [comment]
May help in this case.
